# Generated by Django 4.1.2 on 2022-10-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='text_color',
        ),
        migrations.AddField(
            model_name='myuser',
            name='username_color',
            field=models.CharField(default='black', max_length=255, verbose_name='Цвет логина'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='background_color',
            field=models.CharField(default='white', max_length=255, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='passed_test_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Пройденные тесты'),
        ),
    ]
